# Generated by Django 3.1.8 on 2021-07-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feed_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
